### ISSUE TITLE
Question - open to support swift on linux with this?

### ISSUE THREAD

**Issue by heckj** [kean/FutureX#11]
I was looking around at promise style libraries to help solve a problem in another project, and wanted to utilize this library. It's pretty close, but doesn't currently easily (and consistently) support swift on linux out of the box. I'm willing to make some tweaks and updates to enable that, but wanted to inquire first if that would be acceptable.

I've offered a partial (small) update to Package.swift in #10 - but I'd like to take it a bit further based on my initial exploration:
- [x] update the tests to push them slightly lower (into a subdirectory) to more easily exclude the Host IOS app
- [x] add `swift test` to macOS command line to validate that continues to work as expected (not just through `xcodebuild`)
- [x] add linux focused CI running the tests (in either .travis or .github actions, if you have a preference)
- [x] replace the arc4random usage in the test extensions with a more platform neutral https://developer.apple.com/documentation/swift/randomnumbergenerator

**Comment by kean** [comment]
Please, go ahead, I would appreciate if you could add Linux support.

**Comment by heckj** [comment]
I couldn't vet the linux CI without some tweaking, so I saved that for last, will temp enable it on branches, but I vetted the code with:

    swift test # checkin' mac local
    brew install iainsmith/formulae/swift-docker # handy tool
    swift docker test --args --enable-test-discovery # checkin' linux w/ swift 5.2
